template: Hello, %s!
defaultName: Stranger

#OAUTH2 settings
oauth2:
  keyAlias: myrsakey
  keystorePassword: password
  keyPassword: password
  keystoreFilename: keyStoreFileName.jks

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    sk.fri.uniza: DEBUG

    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: DEBUG

#Views
viewRendererConfiguration:
  freemarker:
    strict_syntax: false
    default_encoding: UTF-8

#Server configuration.
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8085
    - type: https
      port: 8445
      keyStorePath: dwstart.keystore
      keyStorePassword: crimson
      validateCerts: false
  adminConnectors:
      - type: http
        port: 8084

#Database
database:
  # the name of your JDBC driver
  driverClass: org.mariadb.jdbc.Driver

  # the username
  user: windfarmdemo

  # the password
  password: G1PpyytVE8Zy8kHE

  # the JDBC URL
  url: jdbc:mariadb://localhost:3306/windfarmdemoDB

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate.hbm2ddl.auto: create
    hibernate.show_sql: true

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

#Swagger documentation builder
#https://github.com/smoketurner/dropwizard-swagger
swagger:
  resourcePackage: sk.fri.uniza.resources
  title: WindFarmDemo microservices
  schemes: ["http","https"]
  uriPrefix: "/api"
  oauth2:
    clientId: client1
    clientSecrete: 123456
    appName: WindFarmDemo
    realm: JWT